### ISSUE TITLE
I do all thing to deploy a demo on radio, but the server can not load the model

### ISSUE THREAD

**Issue by chengfengke** [OpenGVLab/InternVL#173]
<img width="740" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/56249816/d83bf7d4-b2fe-47dd-8198-af20f76d899f">
<img width="798" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/56249816/da86109d-238f-4c27-8db1-1edcc3b4c0c6">

**Comment by czczup** [comment]
Is there any error message when starting the model worker?

**Comment by chengfengke** [comment]
2024-05-17 15:30:19 | ERROR | stderr | Traceback (most recent call last):
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/internvl/lib/python3.10/runpy.py", line 196, in _run_module_as_main
2024-05-17 15:30:19 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/internvl/lib/python3.10/runpy.py", line 86, in _run_code
2024-05-17 15:30:19 | ERROR | stderr |     exec(code, run_globals)
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/Documents/zxh/InternVL/internvl_chat/internvl/serve/model_worker.py", line 307, in <module>
2024-05-17 15:30:19 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/Documents/zxh/InternVL/internvl_chat/internvl/serve/model_worker.py", line 75, in __init__
2024-05-17 15:30:19 | ERROR | stderr |     self.model = InternVLChatModel.from_pretrained(
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/internvl/lib/python3.10/site-packages/transformers/modeling_utils.py", line 3075, in from_pretrained
2024-05-17 15:30:19 | ERROR | stderr |     config, model_kwargs = cls.config_class.from_pretrained(
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/internvl/lib/python3.10/site-packages/transformers/configuration_utils.py", line 612, in from_pretrained
2024-05-17 15:30:19 | ERROR | stderr |     return cls.from_dict(config_dict, **kwargs)
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/anaconda3/envs/internvl/lib/python3.10/site-packages/transformers/configuration_utils.py", line 764, in from_dict
2024-05-17 15:30:19 | ERROR | stderr |     config = cls(**config_dict)
2024-05-17 15:30:19 | ERROR | stderr |   File "/home/ubuntu/Documents/zxh/InternVL/internvl_chat/internvl/model/internvl_chat/configuration_internvl_chat.py", line 51, in __init__
2024-05-17 15:30:19 | ERROR | stderr |     if llm_config['architectures'][0] == 'LlamaForCausalLM':
2024-05-17 15:30:19 | ERROR | stderr | KeyError: 'architectures'。Now I got this.

**Comment by chengfengke** [comment]
![image](https://github.com/OpenGVLab/InternVL/assets/56249816/80f5102c-0693-4760-8cbf-b071d3564281)
is this the architectures?

**Comment by chengfengke** [comment]
<img width="1104" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/56249816/34f3f212-422b-48fd-9bcc-77f9f166a46a">
now I got this when I use lmdeploy

**Comment by czczup** [comment]
Hello, thank you for your attention. You can now deploy the InternVL2 model following this document: [https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html](https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html)
