### ISSUE TITLE
运行本地demo时发生错误，恳请帮助，谢谢。

### ISSUE THREAD

**Issue by ysyx2008** [OpenGVLab/InternVL#204]
已按要求完成环境部署，按照文档 How to deploy a local demo? 的说明运行时出现以下异常。

(internvl) yushen@user-MS-7E06:~/ai/InternVL/internvl_chat_llava$ python -m llava.serve.gradio_web_server --controller http://0.0.0.0:10000 --model-list-mode reload --device auto
2024-05-24 15:14:59 | ERROR | stderr | Traceback (most recent call last):
2024-05-24 15:14:59 | ERROR | stderr |   File "/home/yushen/micromamba/envs/internvl/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-05-24 15:14:59 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-05-24 15:14:59 | ERROR | stderr |   File "/home/yushen/micromamba/envs/internvl/lib/python3.9/runpy.py", line 87, in _run_code
2024-05-24 15:14:59 | ERROR | stderr |     exec(code, run_globals)
2024-05-24 15:14:59 | ERROR | stderr |   File "/home/yushen/ai/InternVL/internvl_chat_llava/llava/serve/gradio_web_server.py", line 22, in <module>
2024-05-24 15:14:59 | ERROR | stderr |     no_change_btn = gr.Button.update()
2024-05-24 15:14:59 | ERROR | stderr | AttributeError: type object 'Button' has no attribute 'update'
2024-05-24 15:15:00 | INFO | httpx | HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"

**Comment by ysyx2008** [comment]
好像是环境没有按要求安装。。。我再试试。

**Comment by ysyx2008** [comment]
是gradio的版本问题吗？使用的最新的4.31.5

**Comment by ysyx2008** [comment]
测试了gradio 4.0、3.50版本，都不能启动

**Comment by TonyLee1256** [comment]
我也碰到一样的错误了

**Comment by JayZhao315** [comment]
You are using gradio version 3.50.2

这个版本可以

**Comment by Z-Mooz** [comment]
> You are using gradio version 3.50.2
> 
> 这个版本可以

运行起来占用了多少GPU显存

**Comment by JayZhao315** [comment]
> > 您正在使用 gradio 版本 3.50.2
> > 这个版本可以
> 
> 运行起来占用了多少GPU显存

55g显存占用

**Comment by czczup** [comment]
是gradio版本的问题，可以参考这个文件中的版本进行安装：https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat_llava/pyproject.toml

<img width="651" alt="image" src="https://github.com/OpenGVLab/InternVL/assets/23737120/8528e21d-814b-40b9-84ea-04f9e0379cfd">
