### ISSUE TITLE
Key Error loading OpenGVLab/Mini-InternVL-Chat-4B-V1-5

### ISSUE THREAD

**Issue by 17Skye17** [OpenGVLab/InternVL#230]
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/home/xingzhang/Storyboard2Vid/Storyboard2Vid/data_preprocessing/subject_ext/InternVL/example.py", line 8, in <module>
    pipe = pipeline('OpenGVLab/Mini-InternVL-Chat-4B-V1-5')
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/api.py", line 94, in pipeline
    return pipeline_class(model_path,
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/serve/vl_async_engine.py", line 21, in __init__
    super().__init__(model_path, **kwargs)
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 206, in __init__
    self._build_turbomind(model_path=model_path,
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 253, in _build_turbomind
    self.engine = tm.TurboMind.from_pretrained(
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 387, in from_pretrained
    return cls(model_path=pretrained_model_name_or_path,
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 161, in __init__
    self.model_comm = self._from_hf(model_source=model_source,
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/turbomind/turbomind.py", line 267, in _from_hf
    input_model = INPUT_MODELS.get(inferred_model_format)(
  File "/home/xingzhang/miniconda3/envs/internvl/lib/python3.9/site-packages/lmdeploy/turbomind/deploy/source_model/internvl.py", line 42, in __init__
    self.Reader = _readers[arch]
KeyError: 'Phi3ForCausalLM'

**Comment by wanghanyang123** [comment]
+1，请问解决了吗？

**Comment by Win-Rp** [comment]
+1 怎么解决呢？

**Comment by blueHF** [comment]
+1

**Comment by shen518608** [comment]
+1

**Comment by shen518608** [comment]
+1

**Comment by lvhan028** [comment]
LMDeploy 的 turbomind engine 还没有支持 phi-3

**Comment by diegoflip** [comment]
+1

**Comment by Weiyun1025** [comment]
您好，LMDeploy的pytorch engine才支持phi3模型，具体使用方案可以参考我们最新的README

**Comment by czczup** [comment]
可以按照这个文档来部署InternVL2-4B模型：https://internvl.readthedocs.io/en/latest/internvl2.0/deployment.html#launch-service
