### ISSUE TITLE
please install petrel_client

### ISSUE THREAD

**Issue by liming-ai** [OpenGVLab/InternVL#243]
After downloading all the checkpoints and install all the packages as the instruction, I try to run local demo of InternVL v1.5 by:
```
python3 -m internvl.serve.model_worker --host 0.0.0.0 --controller http://localhost:4007 --port 2333 --worker http://localhost:4007 --model-path OpenGVLab/InternVL-Chat-V1-5
```

But there are errors:
```
2024-06-05 02:35:42 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=2333, worker_address='http://localhost:4007', controller_address='http://localhost:4007', model_path='OpenGVLab/InternVL-Chat-V1-5', model_base=None, model_name=None, device='cuda', multi_modal=False, limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=False, load_4bit=False)
2024-06-05 02:35:42 | INFO | model_worker | Loading the model InternVL-Chat-V1-5 on worker f7a2ba ...
2024-06-05 02:35:42 | ERROR | stderr | /home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
2024-06-05 02:35:42 | ERROR | stderr |   warnings.warn(
2024-06-05 02:35:42 | WARNING | transformers.tokenization_utils_base | Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-06-05 02:35:42 | WARNING | transformers.tokenization_utils_base | Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
2024-06-05 02:35:42 | INFO | internvl.model.internvl_chat.configuration_internvl_chat | vision_select_layer: -1
2024-06-05 02:35:42 | INFO | internvl.model.internvl_chat.configuration_internvl_chat | ps_version: v2
2024-06-05 02:35:42 | INFO | internvl.model.internvl_chat.configuration_internvl_chat | min_dynamic_patch: 1
2024-06-05 02:35:42 | INFO | internvl.model.internvl_chat.configuration_internvl_chat | max_dynamic_patch: 12
2024-06-05 02:35:43 | INFO | internvl.model.internvl_chat.modeling_internvl_chat | num_image_token: 256
2024-06-05 02:35:43 | INFO | internvl.model.internvl_chat.modeling_internvl_chat | ps_version: v2
2024-06-05 02:35:43 | ERROR | stderr | 
Loading checkpoint shards:   0%|                                                                                       | 0/11 [00:00<?, ?it/s]
2024-06-05 02:35:44 | ERROR | stderr | 
Loading checkpoint shards:   9%|███████▏                                                                       | 1/11 [00:00<00:05,  1.87it/s]
2024-06-05 02:35:44 | ERROR | stderr | 
Loading checkpoint shards:  18%|██████████████▎                                                                | 2/11 [00:01<00:04,  1.85it/s]
2024-06-05 02:35:45 | ERROR | stderr | 
Loading checkpoint shards:  27%|█████████████████████▌                                                         | 3/11 [00:01<00:04,  1.90it/s]
2024-06-05 02:35:45 | ERROR | stderr | 
Loading checkpoint shards:  36%|████████████████████████████▋                                                  | 4/11 [00:02<00:03,  1.93it/s]
2024-06-05 02:35:46 | ERROR | stderr | 
Loading checkpoint shards:  45%|███████████████████████████████████▉                                           | 5/11 [00:02<00:03,  1.96it/s]
2024-06-05 02:35:46 | ERROR | stderr | 
Loading checkpoint shards:  55%|███████████████████████████████████████████                                    | 6/11 [00:03<00:02,  1.99it/s]
2024-06-05 02:35:47 | ERROR | stderr | 
Loading checkpoint shards:  64%|██████████████████████████████████████████████████▎                            | 7/11 [00:03<00:01,  2.00it/s]
2024-06-05 02:35:47 | ERROR | stderr | 
Loading checkpoint shards:  73%|█████████████████████████████████████████████████████████▍                     | 8/11 [00:04<00:01,  2.08it/s]
2024-06-05 02:35:48 | ERROR | stderr | 
Loading checkpoint shards:  82%|████████████████████████████████████████████████████████████████▋              | 9/11 [00:04<00:00,  2.11it/s]
2024-06-05 02:35:48 | ERROR | stderr | 
Loading checkpoint shards:  91%|██████████████████████████████████████████████████████████████████████▉       | 10/11 [00:04<00:00,  2.15it/s]
2024-06-05 02:35:48 | ERROR | stderr | 
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████| 11/11 [00:05<00:00,  2.56it/s]
2024-06-05 02:35:48 | ERROR | stderr | 
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████| 11/11 [00:05<00:00,  2.14it/s]
2024-06-05 02:35:48 | ERROR | stderr | 
2024-06-05 02:36:00 | INFO | model_worker | Register to controller
2024-06-05 02:36:00 | ERROR | stderr | Traceback (most recent call last):
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
2024-06-05 02:36:00 | ERROR | stderr |     conn = connection.create_connection(
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
2024-06-05 02:36:00 | ERROR | stderr |     raise err
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
2024-06-05 02:36:00 | ERROR | stderr |     sock.connect(sa)
2024-06-05 02:36:00 | ERROR | stderr | ConnectionRefusedError: [Errno 111] Connection refused
2024-06-05 02:36:00 | ERROR | stderr | 
2024-06-05 02:36:00 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-05 02:36:00 | ERROR | stderr | 
2024-06-05 02:36:00 | ERROR | stderr | Traceback (most recent call last):
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/connectionpool.py", line 715, in urlopen
2024-06-05 02:36:00 | ERROR | stderr |     httplib_response = self._make_request(
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/connectionpool.py", line 416, in _make_request
2024-06-05 02:36:00 | ERROR | stderr |     conn.request(method, url, **httplib_request_kw)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/connection.py", line 244, in request
2024-06-05 02:36:00 | ERROR | stderr |     super(HTTPConnection, self).request(method, url, body=body, headers=headers)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/http/client.py", line 1285, in request
2024-06-05 02:36:00 | ERROR | stderr |     self._send_request(method, url, body, headers, encode_chunked)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/http/client.py", line 1331, in _send_request
2024-06-05 02:36:00 | ERROR | stderr |     self.endheaders(body, encode_chunked=encode_chunked)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/http/client.py", line 1280, in endheaders
2024-06-05 02:36:00 | ERROR | stderr |     self._send_output(message_body, encode_chunked=encode_chunked)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/http/client.py", line 1040, in _send_output
2024-06-05 02:36:00 | ERROR | stderr |     self.send(msg)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/http/client.py", line 980, in send
2024-06-05 02:36:00 | ERROR | stderr |     self.connect()
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/connection.py", line 205, in connect
2024-06-05 02:36:00 | ERROR | stderr |     conn = self._new_conn()
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
2024-06-05 02:36:00 | ERROR | stderr |     raise NewConnectionError(
2024-06-05 02:36:00 | ERROR | stderr | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7feadf393340>: Failed to establish a new connection: [Errno 111] Connection refused
2024-06-05 02:36:00 | ERROR | stderr | 
2024-06-05 02:36:00 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-05 02:36:00 | ERROR | stderr | 
2024-06-05 02:36:00 | ERROR | stderr | Traceback (most recent call last):
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/requests/adapters.py", line 489, in send
2024-06-05 02:36:00 | ERROR | stderr |     resp = conn.urlopen(
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/connectionpool.py", line 799, in urlopen
2024-06-05 02:36:00 | ERROR | stderr |     retries = retries.increment(
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
2024-06-05 02:36:00 | ERROR | stderr |     raise MaxRetryError(_pool, url, error or ResponseError(cause))
2024-06-05 02:36:00 | ERROR | stderr | urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4007): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feadf393340>: Failed to establish a new connection: [Errno 111] Connection refused'))
2024-06-05 02:36:00 | ERROR | stderr | 
2024-06-05 02:36:00 | ERROR | stderr | During handling of the above exception, another exception occurred:
2024-06-05 02:36:00 | ERROR | stderr | 
2024-06-05 02:36:00 | ERROR | stderr | Traceback (most recent call last):
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-06-05 02:36:00 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/runpy.py", line 87, in _run_code
2024-06-05 02:36:00 | ERROR | stderr |     exec(code, run_globals)
2024-06-05 02:36:00 | ERROR | stderr |   File "/mnt/bn/sijie-us-nas-8/liming/code/InternVL/internvl_chat/internvl/serve/model_worker.py", line 309, in <module>
2024-06-05 02:36:00 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-06-05 02:36:00 | ERROR | stderr |   File "/mnt/bn/sijie-us-nas-8/liming/code/InternVL/internvl_chat/internvl/serve/model_worker.py", line 88, in __init__
2024-06-05 02:36:00 | ERROR | stderr |     self.register_to_controller()
2024-06-05 02:36:00 | ERROR | stderr |   File "/mnt/bn/sijie-us-nas-8/liming/code/InternVL/internvl_chat/internvl/serve/model_worker.py", line 102, in register_to_controller
2024-06-05 02:36:00 | ERROR | stderr |     r = requests.post(url, json=data)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/requests/api.py", line 115, in post
2024-06-05 02:36:00 | ERROR | stderr |     return request("post", url, data=data, json=json, **kwargs)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/requests/api.py", line 59, in request
2024-06-05 02:36:00 | ERROR | stderr |     return session.request(method=method, url=url, **kwargs)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/requests/sessions.py", line 587, in request
2024-06-05 02:36:00 | ERROR | stderr |     resp = self.send(prep, **send_kwargs)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/requests/sessions.py", line 701, in send
2024-06-05 02:36:00 | ERROR | stderr |     r = adapter.send(request, **kwargs)
2024-06-05 02:36:00 | ERROR | stderr |   File "/home/tiger/miniconda3/envs/internvl/lib/python3.9/site-packages/requests/adapters.py", line 565, in send
2024-06-05 02:36:00 | ERROR | stderr |     raise ConnectionError(e, request=request)
2024-06-05 02:36:00 | ERROR | stderr | requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=4007): Max retries exceeded with url: /register_worker (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7feadf393340>: Failed to establish a new connection: [Errno 111] Connection refused'))

```

**Comment by njzfw1024** [comment]
> Connection refused

检查一下端口号呢

**Comment by czczup** [comment]
`please install petrel_client`是个warning，可以忽略。这个感觉还是设置了代理或者是端口的问题
