### ISSUE TITLE
install with seldon-core run erro

### ISSUE THREAD

**Issue by diandianliu** [OpenGVLab/InternVL#249]
Hi
I install the  env by https://github.com/OpenGVLab/InternVL/blob/main/INSTALLATION.md  and  run successful.
But  After I install the seldon-core, run error
**error mesage:**
Traceback (most recent call last):                                                                                                          
  File "/workspace/itvl1.5-v100-test/demo_2b_liu.py", line 88, in <module>                                                                  
    model = AutoModel.from_pretrained(                                                                                                      
  File "/root/anaconda3/envs/internvl/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 553, in from_pretrained   
    model_class = get_class_from_dynamic_module(                                                                                            
  File "/root/anaconda3/envs/internvl/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 488, in get_class_from_dynamic
_module                                                                                                                                     
    final_module = get_cached_module_file(                                                                                                  
  File "/root/anaconda3/envs/internvl/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 315, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)                                                                                    
  File "/root/anaconda3/envs/internvl/lib/python3.9/site-packages/transformers/dynamic_module_utils.py", line 180, in check_imports         
    raise ImportError(                                                                                                                      
ImportError: This modeling file requires the following packages that were not found in your environment: peft. Run `pip install peft`

--------
pip install peft  also the same error

**Comment by diandianliu** [comment]
the following dependency conflicts.
seldon-core 1.18.2 requires setuptools>=65.5.1, but you have setuptools 60.2.0 which is incompatible.

**Comment by xylovezxy** [comment]
Excuse me, have you encountered this error message：
AttributeError: model'transformers_modules. configuration_internvl_chat 'has no attribute' InternVLChatConfiguration '

**Comment by diandianliu** [comment]
> Excuse me, have you encountered this error message： AttributeError: model'transformers_modules. configuration_internvl_chat 'has no attribute' InternVLChatConfiguration '

no

**Comment by czczup** [comment]
This issue has been inactive for two months, so I am closing it. If you have any further questions or encounter any problems, please feel free to reopen it. Thank you!
