### ISSUE TITLE
How to use OpenGVLab/InternVL Chat ViT-6B-Vicuna-7B model for inference

### ISSUE THREAD

**Issue by chenchun0629** [OpenGVLab/InternVL#27]
When I use the llava command line for deployment, an error message occurs.

Can you provide some advice?

Thank you to the excellent work of the OpenGVLab team.

```
$ python -m llava.serve.model_worker --host 0.0.0.0 --controller http://localhost:12000 --port 42000 --worker http://localhost:42000 --model-path /data/jupyter/user/cc/llm_models/
InternVL-Chat-ViT-6B-Vicuna-7B/
2024-01-05 14:23:13 | INFO | model_worker | args: Namespace(host='0.0.0.0', port=42000, worker_address='http://localhost:42000', controller_address='http://localhost:12000', model_path='/data/jupyter/user/cc/llm_models/InternVL-Chat-ViT-6B-Vicuna-7B/', model_base=None, model_name=None, device='cuda', multi_modal=False, limit_model_concurrency=5, stream_interval=1, no_register=False, load_8bit=False, load_4bit=False)
2024-01-05 14:23:13 | INFO | model_worker | Loading the model InternVL-Chat-ViT-6B-Vicuna-7B on worker 921a64 ...
2024-01-05 14:23:13 | ERROR | stderr | Traceback (most recent call last):
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/runpy.py", line 197, in _run_module_as_main
2024-01-05 14:23:13 | ERROR | stderr |     return _run_code(code, main_globals, None,
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/runpy.py", line 87, in _run_code
2024-01-05 14:23:13 | ERROR | stderr |     exec(code, run_globals)
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/jupyter/user/cc/InternVL/llava/llava/serve/model_worker.py", line 275, in <module>
2024-01-05 14:23:13 | ERROR | stderr |     worker = ModelWorker(args.controller_address,
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/jupyter/user/cc/InternVL/llava/llava/serve/model_worker.py", line 65, in __init__
2024-01-05 14:23:13 | ERROR | stderr |     self.tokenizer, self.model, self.image_processor, self.context_len = load_pretrained_model(
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/jupyter/user/cc/InternVL/llava/llava/model/builder.py", line 102, in load_pretrained_model
2024-01-05 14:23:13 | ERROR | stderr |     tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/models/auto/tokenization_auto.py", line 727, in from_pretrained
2024-01-05 14:23:13 | ERROR | stderr |     return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 1854, in from_pretrained
2024-01-05 14:23:13 | ERROR | stderr |     return cls._from_pretrained(
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2017, in _from_pretrained
2024-01-05 14:23:13 | ERROR | stderr |     tokenizer = cls(*init_inputs, **init_kwargs)
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 156, in __init__
2024-01-05 14:23:13 | ERROR | stderr |     self.sp_model = self.get_spm_processor()
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/models/llama/tokenization_llama.py", line 164, in get_spm_processor
2024-01-05 14:23:13 | ERROR | stderr |     model_pb2 = import_protobuf()
2024-01-05 14:23:13 | ERROR | stderr |   File "/data/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/convert_slow_tokenizer.py", line 40, in import_protobuf
2024-01-05 14:23:13 | ERROR | stderr |     return sentencepiece_model_pb2
2024-01-05 14:23:13 | ERROR | stderr | UnboundLocalError: local variable 'sentencepiece_model_pb2' referenced before assignment
```

**Comment by chenchun0629** [comment]
```
transformers              4.32.0
torch                     2.0.1
torchaudio                2.0.2
torchvision               0.15.2
flash-attn                0.2.8
apex                      0.1
llava                     1.1.1        /data/jupyter/user/cc/InternVL/llava
```

**Comment by chenchun0629** [comment]
```
pip install protobuf
```
