### ISSUE TITLE
运行local demo报错

### ISSUE THREAD

**Issue by gangxu822** [OpenGVLab/InternVL#281]
这个报错是什么原因：2024-06-18 21:15:14 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"
2024-06-18 21:15:23 | ERROR | asyncio | Task exception was never retrieved
future: <Task finished name='531q8lzkbp_11' coro=<Queue.process_events() done, defined at /usr/local/lib/python3.9/dist-packages/gradio/queueing.py:342> exception=1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': '531q8lzkbp'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 346, in process_events
    client_awake = await self.gather_event_data(event)
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 219, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "/usr/local/lib/python3.9/dist-packages/gradio/queueing.py", line 448, in get_message
    return PredictBody(**data), True
  File "/usr/local/lib/python3.9/dist-packages/pydantic/main.py", line 176, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for PredictBody
event_id
  Field required [type=missing, input_value={'data': [], 'event_data'...ion_hash': '531q8lzkbp'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.7/v/missing
2024-06-18 21:15:23 | INFO | httpx | HTTP Request: POST http://localhost:7860/reset "HTTP/1.1 200 OK"

**Comment by gangxu822** [comment]
now is this

**Comment by gangxu822** [comment]
NETWORK ERROR DUE TO HIGH TRAFFIC. PLEASE REGENERATE OR REFRESH THIS PAGE.

**Comment by czczup** [comment]
您好，这个应该是环境里一些包的版本问题，您可以和这里对齐一下版本：
https://github.com/OpenGVLab/InternVL/blob/main/internvl_chat/pyproject.toml

**Comment by gangxu822** [comment]
好的，我先看下微调，后续有问题再请教下

**Comment by Arthurwyf** [comment]
你看看安装的flash-attn，可能不支持

**Comment by czczup** [comment]
可以试试看部署这个新的local demo: https://internvl.readthedocs.io/en/latest/get_started/local_chat_demo.html
