### ISSUE TITLE
InternVL-Chat-V1-5-Int8的加载模型报错

### ISSUE THREAD

**Issue by Iven2166** [OpenGVLab/InternVL#346]
我在 modelscope下载了 https://modelscope.cn/models/AI-ModelScope/InternVL-Chat-V1-5-Int8 的量化版本，使用PPU 进行推理。transformers==4.37.2

请问为何会出现以下报错？

```python
Traceback (most recent call last):
  File "demo2.py", line 89, in <module>
    model = AutoModel.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3850, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 4284, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 830, in _load_state_dict_into_meta_model
    set_module_quantized_tensor_to_device(
  File "/opt/conda/lib/python3.8/site-packages/transformers/integrations/bitsandbytes.py", line 102, in set_module_quantized_tensor_to_device
    setattr(new_value, "SCB", quantized_stats["SCB"].to(device))
RuntimeError: CUDA error: unspecified launch failure
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

**Comment by whai362** [comment]
看着是pytorch cuda版安装没有成功
