### ISSUE TITLE
4张V100，InternVL-G推理超显存，或者没有自动映射

### ISSUE THREAD

**Issue by ycfate** [OpenGVLab/InternVL#370]
按照官方的transformers推理代码，用4张v100进行IntrenVL-G推理，超过2张图就会超显存，一张图会提示不在一个device上
`Traceback (most recent call last):
  File "filter_captions.py", line 35, in <module>
    filters_outputs_temp = filter_captions(args.filter_model_name, model, image_processor, tokenizer, captions, prefix=None, ocr_prefix=None, threshold=0.5)
  File "/ossfs/workspace/DataCentric/filters/filter_utils.py", line 94, in filter_captions
    logits_per_image, logits_per_text = model(image=pixel_values, text=input_ids, mode='InternVL-G')
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_internvl.py", line 422, in forward
    image_features = self.encode_image(image, mode)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_internvl.py", line 392, in encode_image
    backbone_embeds, image_embeds = self.get_image_features(
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_internvl.py", line 350, in get_image_features
    vision_outputs = self.vision_model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 327, in forward
    encoder_outputs = self.encoder(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 264, in forward
    layer_outputs = encoder_layer(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 206, in forward
    hidden_states = hidden_states + self.drop_path1(self.attn(self.norm1(hidden_states)) * self.ls1)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL-14B-224px/modeling_intern_vit.py", line 44, in forward
    return self.weight * hidden_states.to(input_dtype)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!`

**Comment by ycfate** [comment]
而且4张卡似乎只使用前两张

**Comment by ycfate** [comment]
是不是需要自己做显卡映射，单卡v100似乎不够推理多张图
