### ISSUE TITLE
[ModelScope][InternVL2-4B]torch.cuda.OutOfMemoryError: CUDA out of memory.

### ISSUE THREAD

**Issue by zjykzj** [OpenGVLab/InternVL#380]
I have 2*3090 (24GB), but when running the sample program, I only used a single card and encountered an error during operation.

```text
Traceback (most recent call last):
  File "/data/zj/llm/LLMSamples/internvl-4b.py", line 335, in <module>
    response, history = model.chat(tokenizer, pixel_values, question, generation_config,
  File "/home/user/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_internvl_chat.py", line 263, in chat
    generation_output = self.generate(
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_internvl_chat.py", line 313, in generate
    outputs = self.language_model.generate(
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/transformers/generation/utils.py", line 1479, in generate
    return self.greedy_search(
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/transformers/generation/utils.py", line 2340, in greedy_search
    outputs = self(
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_phi3.py", line 1281, in forward
    outputs = self.model(
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_phi3.py", line 1159, in forward
    layer_outputs = decoder_layer(
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_phi3.py", line 880, in forward
    attn_outputs, self_attn_weights, present_key_value = self.self_attn(
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/user/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_phi3.py", line 400, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(value_states.dtype)
  File "/home/user/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/nn/functional.py", line 1845, in softmax
    ret = input.softmax(dim, dtype=dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 4.70 GiB (GPU 0; 23.69 GiB total capacity; 15.36 GiB already allocated; 3.32 GiB free; 20.05 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Example program from: [https://modelscope.cn/models/OpenGVLab/InternVL2-4B](https://modelscope.cn/models/OpenGVLab/InternVL2-4B) The `Quick Start` section.

```text
import torch
import torchvision.transforms as T
from PIL import Image
from torchvision.transforms.functional import InterpolationMode
from transformers import AutoModel, AutoTokenizer

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)


...
...


path = 'OpenGVLab/InternVL2-4B'
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    trust_remote_code=True).eval().cuda()

tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True)
# set the max number of tiles in `max_num`
pixel_values = load_image('./examples/image1.jpg', max_num=6).to(torch.bfloat16).cuda()

generation_config = dict(
    num_beams=1,
    max_new_tokens=1024,
    do_sample=False,
)

# pure-text conversation (纯文本对话)
question = 'Hello, who are you?'
response, history = model.chat(tokenizer, None, question, generation_config, history=None, return_history=True)
print(f'User: {question}')
print(f'Assistant: {response}')

...
...
```

How can we achieve multi-GPUs inference? @lvhan028 @shepnerd @whai362 @orashi @czczup

**Comment by feihuamantian** [comment]
https://github.com/OpenGVLab/InternVL/issues/351
