### ISSUE TITLE
4B model conda enviroment Issue on page /internvl2.0/finetune.html

### ISSUE THREAD

**Issue by caffeineWoo** [OpenGVLab/InternVL#445]
### Installation and Runtime Issues with LORA finetune on Multi-GPU Setup
If you know the compatible versions of CUDA, Torch, and NCCL that can be used without conflicts on RTX A5000 & Ubuntu 22.04, or if you have experience with a well-functioning environment, please share that information.

#### System Configuration (individually 2 cases, Not a same time.)
- **Environment**: Conda
- **Python Versions**: 3.12 and 3.10
- **CUDA Versions**: 12.4 and 12.1
- **NCCL Versions**:
  - CUDA 12.4: (2, 20, 5)
  - CUDA 12.1: (2, 13, 3)
- **GPUs**: 2x RTX A5000 and 2x RTX A5000

#### Steps to Reproduce
1. Create a Conda environment:
    ```sh
    conda create -n internvl_env python=3.12
    conda activate internvl_env
    ```
2. Install requirements:
    ```sh
    pip install -r requirements.txt
    ```
3. Attempt to run the script:
    ```sh
    GPUS=2 PER_DEVICE_BATCH_SIZE=1 sh shell/internvl2.0/2nd_finetune/internvl2_4b_phi3_3_8b_dynamic_res_2nd_finetune_lora.sh
    ```

#### Issue Description
- On running `pip install -r requirements.txt`, I encounter multiple library conflict errors.
- The same errors occur on two different setups:
  - Python 3.12 with CUDA 12.4 and NCCL version (2, 20, 5)
  - Python 3.10 with CUDA 12.1 and NCCL version (2, 13, 3)
- The setup involves using 2x RTX A5000 GPUs on a single node. (The goal is to run 2 nodes with a total of 4 GPUs, but the errors occur with the current single-node dual-GPU configuration.)

#### Error Log
```
[2024-08-01 12:22:32,692] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-08-01 12:22:32,692] [INFO] [real_accelerator.py:191:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/home/ai-pc/Desktop/InternVL/internvl_chat/internvl/train/internvl_chat_finetune.py", line 18, in <module>
Traceback (most recent call last):
  File "/home/ai-pc/Desktop/InternVL/internvl_chat/internvl/train/internvl_chat_finetune.py", line 18, in <module>
    from internvl.dist_utils import init_dist
  File "/home/ai-pc/Desktop/InternVL/internvl_chat/internvl/dist_utils.py", line 6, in <module>
    from internvl.dist_utils import init_dist
  File "/home/ai-pc/Desktop/InternVL/internvl_chat/internvl/dist_utils.py", line 6, in <module>
    import deepspeed
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/__init__.py", line 26, in <module>
    import deepspeed
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/__init__.py", line 26, in <module>
    from . import module_inject
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from . import module_inject
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/module_inject/__init__.py", line 6, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 607, in <module>
    from .replace_module import replace_transformer_layer, revert_transformer_layer, ReplaceWithTensorSlicing, GroupQuantizer, generic_injection
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/module_inject/replace_module.py", line 607, in <module>
        from ..pipe import PipelineModulefrom ..pipe import PipelineModule

  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/pipe/__init__.py", line 6, in <module>
        from ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpecfrom ..runtime.pipe import PipelineModule, LayerSpec, TiedLayerSpec

  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/pipe/__init__.py", line 6, in <module>
        from .module import PipelineModule, LayerSpec, TiedLayerSpecfrom .module import PipelineModule, LayerSpec, TiedLayerSpec

  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/pipe/module.py", line 19, in <module>
    from ..activation_checkpointing import checkpointing    
from ..activation_checkpointing import checkpointing
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 26, in <module>
    from deepspeed.runtime.config import DeepSpeedConfig
    from deepspeed.runtime.config import DeepSpeedConfig  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 59, in <module>

  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/config.py", line 59, in <module>
        from ..autotuning.config import DeepSpeedAutotuningConfigfrom ..autotuning.config import DeepSpeedAutotuningConfig

  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/autotuning/__init__.py", line 6, in <module>
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/autotuning/__init__.py", line 6, in <module>
    from .autotuner import Autotuner
    from .autotuner import Autotuner  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/autotuning/autotuner.py", line 20, in <module>

  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/autotuning/autotuner.py", line 20, in <module>
    from .scheduler import ResourceManager
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/autotuning/scheduler.py", line 8, in <module>
    from .scheduler import ResourceManager
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/autotuning/scheduler.py", line 8, in <module>
        from numpy import BUFSIZEfrom numpy import BUFSIZE

ImportError: ImportErrorcannot import name 'BUFSIZE' from 'numpy' (/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/numpy/__init__.py): 
cannot import name 'BUFSIZE' from 'numpy' (/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/numpy/__init__.py)
E0801 12:22:36.783248 133328379762496 torch/distributed/elastic/multiprocessing/api.py:826] failed (exitcode: 1) local_rank: 0 (pid: 62601) of binary: /home/ai-pc/anaconda3/envs/internvl/bin/python
Traceback (most recent call last):
  File "/home/ai-pc/anaconda3/envs/internvl/bin/torchrun", line 10, in <module>
    sys.exit(main())
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/run.py", line 879, in main
    run(args)
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/run.py", line 870, in run
    elastic_launch(
  File "/home/ai-pc/anaconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
```

#### Expected Behavior
- Successful installation of dependencies via `pip install -r requirements.txt`.
- Successful execution of the finetuning script without library conflicts or runtime errors.

#### Additional Context
- Not using Flash Attention 
- Explicitly setting environment variables and ensuring all dependencies are updated does not resolve the issue.

#### Request
- Assistance in resolving library conflicts during installation.
- If you know the compatible versions of CUDA, Torch, and NCCL that can be used without conflicts on RTX A5000 & Ubuntu 22.04, or if you have experience with a well-functioning environment, please share that information.

Thank you for your support.

**Comment by czczup** [comment]
Hello, it seems that the version of numpy is too high.

**Comment by caffeineWoo** [comment]
> Hello, it seems that the version of numpy is too high.

I know. Can you tell me the setup of your Cuda, Torch, graphics drivers, etc.?

**Comment by czczup** [comment]
For this issue, you should be able to resolve it by downgrading the numpy version to below 2.0  (I recommend trying to search for solutions on Google)
