### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:0!

### ISSUE THREAD

**Issue by Xiaolong-RRL** [OpenGVLab/InternVL#478]
This error occurs during the evaluation phase：

Executed command:
`GPUS=4 sh evaluate.sh pretrained/InternVL2-40B mme --dynamic --auto`

The error that occurred:
``` bash
+ MASTER_PORT=63669
+ PORT=63665
+ GPUS=4
+ GPUS_PER_NODE=4
+ NODES=1
+ export MASTER_PORT=63669
+ MASTER_PORT=63669
+ export PORT=63665
+ PORT=63665
+ ARGS=("$@")
+ [[ 1 -gt 0 ]]
+ case "$1" in
+ GPUS=1
+ shift
+ [[ 0 -gt 0 ]]
+ echo 'GPUS: 1'
GPUS: 1
+ python eval.py --checkpoint pretrained/InternVL2-40B --dynamic --auto
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
trainable params: 983,040,000 || all params: 35,372,057,600 || trainable%: 2.7791
Loading checkpoint shards: 100%|██████████████████████████████████████████████████████████████████████████████████| 17/17 [00:49<00:00,  2.92s/it]
[test] total_params: 41.05172416B, use num_beams: 1
[test] image_size: 448
[test] template: Hermes-2-driving
[test] dynamic_image_size: True
[test] use_thumbnail: True
[test] max_num: 6
  0%|                                                                                                                      | 0/50 [00:00<?, ?it/s]dynamic ViT batch size: 3
top_p` is set to `0.9` -- this flag is only used in sample-based generation modes. You should set `do_sample=True` or unset `top_p`.
  warnings.warn(
  0%|                                                                                                                      | 0/50 [00:19<?, ?it/s]
Traceback (most recent call last):
  File "/root/internvl_chat/inference_codalm.py", line 104, in <module>
    response = model.chat(
  File "/root/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py", line 340, in chat
    generation_output = self.generate(
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py", line 390, in generate
    outputs = self.language_model.generate(
  File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 1491, in generate
    outputs = self.base_model.generate(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1479, in generate
    return self.greedy_search(
File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 2380, in greedy_search
    next_tokens = next_tokens * unfinished_sequences + pad_token_id * (1 - unfinished_sequences)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:0!
```

My devices is 4 x a800 (80G), I noticed that the model is loaded on 4 GPUs.

How can I solve this problem?

Thanks！！

**Comment by czczup** [comment]
Hello, thank you for your feedback.

 I just tried to fix this bug on the latest commit, and my local test has passed, please pull the latest code and try it.

**Comment by Xiaolong-RRL** [comment]
Yeap～That works!! Thanks for your quick reply!
