### ISSUE TITLE
[Bug] Getting raise NotImplementedError for model.get_input_embeddings()

### ISSUE THREAD

**Issue by podyss** [OpenGVLab/InternVL#512]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

Getting raise NotImplementedError for model.get_input_embeddings()

### Reproduction

model = AutoModel.from_pretrained("OpenGVLab/InternVL2-2B", trust_remote_code=True)
input_embeddings = model.get_input_embeddings()

### Environment

```Shell
Python: 3.11.9
torch: 2.4.0
transformers: 4.44.0
```

**Comment by czczup** [comment]
Hello, if you want to get input_embeddings for the language model, you can use `model.language_model.get_input_embeddings()`.

**Comment by snowyrain** [comment]
> Hello, if you want to get input_embeddings for the language model, you can use `model.language_model.get_input_embeddings()`.

I have the same question in internvl_chat_dpo.py. how to fix it? THK

**Comment by snowyrain** [comment]
> Hello, if you want to get input_embeddings for the language model, you can use `model.language_model.get_input_embeddings()`.

我在训练internvl_chat_dpo时遇到了一样的报错，请问因该如何解决呢，是不是代码bug，transformer我用的是官方提供的版本。报错是
Traceback (most recent call last):
  File "internvl/train/internvl_chat_dpo.py", line 1060, in <module>
    main()
  File "internvl/train/internvl_chat_dpo.py", line 1013, in main
    trainer = MultimodalDPOTrainer(
  File "/ossfs/workspace/zxy/InternVL/internvl_chat/internvl/train/trainer_dpo.py", line 27, in __init__
    super().__init__(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/trl/trainer/dpo_trainer.py", line 302, in __init__
    model.enable_input_require_grads()
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1580, in enable_input_require_grads
    self._require_grads_hook = self.get_input_embeddings().register_forward_hook(make_inputs_require_grads)
  File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1599, in get_input_embeddings
    raise NotImplementedError
NotImplementedError

**Comment by snowyrain** [comment]
> Hello, if you want to get input_embeddings for the language model, you can use `model.language_model.get_input_embeddings()`.

我在训练internvl_chat_dpo时遇到了一样的报错，请问因该如何解决呢，是不是代码bug，transformer我用的是官方提供的版本。报错是
Traceback (most recent call last):
File "internvl/train/internvl_chat_dpo.py", line 1060, in
main()
File "internvl/train/internvl_chat_dpo.py", line 1013, in main
trainer = MultimodalDPOTrainer(
File "trainer_dpo.py", line 27, in init
super().init(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/huggingface_hub/utils/_deprecation.py", line 101, in inner_f
return f(*args, **kwargs)
File "/opt/conda/lib/python3.8/site-packages/trl/trainer/dpo_trainer.py", line 302, in init
model.enable_input_require_grads()
File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1580, in enable_input_require_grads
self._require_grads_hook = self.get_input_embeddings().register_forward_hook(make_inputs_require_grads)
File "/opt/conda/lib/python3.8/site-packages/transformers/modeling_utils.py", line 1599, in get_input_embeddings
raise NotImplementedError
NotImplementedError
