### ISSUE TITLE
[Bug] internvl_g中lora_finetune脚本运行报错

### ISSUE THREAD

**Issue by fangxin2github** [OpenGVLab/InternVL#553]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

运行internvl_g/shell/lora_finetune/internvl_stage2_finetune_flickrcn_224_bs1024_ep10_lora16_4gpu.sh报错，详细sh脚本
`set -x

GPUS=${GPUS:-4}
BATCH_SIZE=${BATCH_SIZE:-1}

export PYTHONPATH="${PYTHONPATH}:$(pwd)"
export MASTER_PORT=34229
export TF_CPP_MIN_LOG_LEVEL=3
export LAUNCHER=pytorch

OUTPUT_DIR='/mnt/data-1/fangxin/projects/internvl/work_dirs/debug'

if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
fi

torchrun \
  --nnodes=1 \
  --node_rank=0 \
  --master_addr=127.0.0.1 \
  --nproc_per_node=${GPUS} \
  --master_port=${MASTER_PORT} \
  internvl/train/internvl_stage2_finetune.py \
  --dataset_name 'flickr30k_cn_train' \
  --model_name_or_path "/mnt/data-1/fangxin/projects/internvl/data/OpenGVLab/InternVL-14B-224px" \
  --output_dir ${OUTPUT_DIR} \
  --overwrite_output_dir True \
  --freeze_model \
  --freeze_vision_model \
  --freeze_qllama \
  --unfreeze_qllama_head \
  --use_backbone_lora 16 \
  --use_qllama_lora 16 \
  --force_image_size 224 \
  --drop_path_rate 0.0 \
  --dataloader_num_workers 2 \
  --pad_to_max_length True \
  --bf16 True \
  --num_train_epochs 10 \
  --per_device_train_batch_size ${BATCH_SIZE} \
  --gradient_accumulation_steps 1 \
  --evaluation_strategy "no" \
  --save_strategy "steps" \
  --save_steps 100 \
  --save_total_limit 5 \
  --learning_rate 1e-6 \
  --weight_decay 0.05 \
  --warmup_steps 100 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --max_seq_length 80 \
  --do_train True \
  --optim adamw_torch \
  --deepspeed "zero_stage1_config.json" \
  --report_to "tensorboard"
`

![1725256605046](https://github.com/user-attachments/assets/240e0fa8-87f4-4f0a-a884-be1c85053d63)
程序终止，但是不显示任何报错信息。

经过debug，发现在transformers的Trainer类下的training_step中的self.accelerator.backward(loss)代码出卡住

### Reproduction

运行上述sh脚本

### Environment

```Shell
absl-py                   2.1.0
accelerate                0.31.0
addict                    2.4.0
aiofiles                  24.1.0
aiohappyeyeballs          2.4.0
aiohttp                   3.10.5
aiosignal                 1.3.1
altair                    5.4.1
annotated-types           0.7.0
anyio                     4.4.0
async-timeout             4.0.3
attrs                     24.2.0
beautifulsoup4            4.12.3
bitsandbytes              0.41.0
blinker                   1.8.2
Brotli                    1.0.9
cachetools                5.5.0
certifi                   2024.7.4
charset-normalizer        3.3.2
click                     8.1.7
colorama                  0.4.6
contourpy                 1.3.0
cycler                    0.12.1
decord                    0.6.0
deepspeed                 0.14.4
einops                    0.6.1
einops-exts               0.0.4
exceptiongroup            1.2.2
fastapi                   0.112.2
ffmpy                     0.4.0
filelock                  3.13.1
flash_attn                2.3.6
fonttools                 4.53.1
frozenlist                1.4.1
fsspec                    2024.6.1
future                    1.0.0
gdown                     5.2.0
gitdb                     4.0.11
GitPython                 3.1.43
gmpy2                     2.1.2
gradio                    3.35.2
gradio_client             0.2.9
grpcio                    1.66.1
h11                       0.14.0
hjson                     3.1.0
httpcore                  0.17.3
httpx                     0.24.0
huggingface-hub           0.24.6
idna                      3.7
imageio                   2.35.1
importlib_metadata        8.4.0
importlib_resources       6.4.4
Jinja2                    3.1.4
joblib                    1.4.2
jsonschema                4.23.0
jsonschema-specifications 2023.12.1
kiwisolver                1.4.5
latex2mathml              3.77.0
linkify-it-py             2.0.3
Markdown                  3.7
markdown-it-py            2.2.0
markdown2                 2.5.0
MarkupSafe                2.1.3
matplotlib                3.9.2
mdit-py-plugins           0.3.3
mdurl                     0.1.2
mkl-fft                   1.3.8
mkl-random                1.2.4
mkl-service               2.4.0
mmcls                     0.25.0
mmcv-full                 1.6.2
mmsegmentation            0.30.0
model-index               0.1.11
mpmath                    1.3.0
multidict                 6.0.5
narwhals                  1.6.0
networkx                  3.2.1
ninja                     1.11.1.1
numpy                     1.26.4
nvidia-cublas-cu12        12.1.3.1
nvidia-cuda-cupti-cu12    12.1.105
nvidia-cuda-nvrtc-cu12    12.1.105
nvidia-cuda-runtime-cu12  12.1.105
nvidia-cudnn-cu12         9.1.0.70
nvidia-cufft-cu12         11.0.2.54
nvidia-curand-cu12        10.3.2.106
nvidia-cusolver-cu12      11.4.5.107
nvidia-cusparse-cu12      12.1.0.106
nvidia-ml-py              12.560.30
nvidia-nccl-cu12          2.20.5
nvidia-nvjitlink-cu12     12.6.68
nvidia-nvtx-cu12          12.1.105
opencv-python             4.10.0.84
opendatalab               0.0.10
openmim                   0.3.9
openxlab                  0.0.11
ordered-set               4.1.0
orjson                    3.10.7
packaging                 24.1
pandas                    2.2.2
peft                      0.12.0
pillow                    10.4.0
pip                       24.2
platformdirs              4.2.2
prettytable               3.11.0
protobuf                  5.28.0
psutil                    6.0.0
py-cpuinfo                9.0.0
pyarrow                   17.0.0
pycocoevalcap             1.2
pycocotools               2.0.8
pycryptodome              3.20.0
pydantic                  2.8.2
pydantic_core             2.20.1
pydeck                    0.9.1
pydub                     0.25.1
Pygments                  2.18.0
pynvml                    11.5.3
pyparsing                 3.1.4
PySocks                   1.7.1
python-dateutil           2.9.0.post0
python-multipart          0.0.9
pytz                      2024.1
PyYAML                    6.0.1
referencing               0.35.1
regex                     2024.7.24
requests                  2.32.3
rich                      13.8.0
rpds-py                   0.20.0
safetensors               0.4.4
scikit-learn              1.5.1
scipy                     1.13.1
semantic-version          2.10.0
sentencepiece             0.1.99
setuptools                72.1.0
shortuuid                 1.0.13
six                       1.16.0
smmap                     5.0.1
sniffio                   1.3.1
soupsieve                 2.6
starlette                 0.38.2
streamlit                 1.38.0
streamlit-image-select    0.6.0
svgwrite                  1.4.3
sympy                     1.13.2
tabulate                  0.9.0
tenacity                  8.5.0
tensorboard               2.17.1
tensorboard-data-server   0.7.2
tensorboardX              2.6.2.2
termcolor                 2.4.0
threadpoolctl             3.5.0
timm                      0.9.12
tokenizers                0.15.1
toml                      0.10.2
tomli                     2.0.1
torch                     2.4.0
torchaudio                2.4.0
torchvision               0.19.0
tornado                   6.4.1
tqdm                      4.66.5
transformers              4.37.2
triton                    3.0.0
typing_extensions         4.11.0
tzdata                    2024.1
uc-micro-py               1.0.3
urllib3                   2.2.2
uvicorn                   0.30.6
watchdog                  4.0.2
wavedrom                  2.0.3.post3
wcwidth                   0.2.13
websockets                13.0.1
Werkzeug                  3.0.4
wheel                     0.43.0
yacs                      0.1.8
yapf                      0.40.1
yarl                      1.9.4
zipp                      3.20.1
```

### Error traceback

```Shell
E0902 14:11:47.447608 140430924072128 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: -8) local_rank: 1 (pid: 1040070) of binary: /home/fangxin/miniconda3/envs/internvl/bin/python
Traceback (most recent call last):
  File "/home/fangxin/miniconda3/envs/internvl/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.0', 'console_scripts', 'torchrun')())
  File "/home/fangxin/miniconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/fangxin/miniconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/run.py", line 901, in main
    run(args)
  File "/home/fangxin/miniconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/home/fangxin/miniconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/fangxin/miniconda3/envs/internvl/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
```

**Comment by ErfeiCui** [comment]
应该是训练环境问题，请参考文档检查一下：https://internvl.readthedocs.io/en/latest/get_started/installation.html

**Comment by fangxin2github** [comment]
> 应该是训练环境问题，请参考文档检查一下：https://internvl.readthedocs.io/en/latest/get_started/installation.html

请问cuda版本推荐多少？

**Comment by HuaYuexia** [comment]
I had the same problem, did you solve it?

**Comment by fangxin2github** [comment]
> I had the same problem, did you solve it?

你用的h20显卡？

**Comment by labor784** [comment]
你好，我遇到了同样的问题，请问你解决了吗？

**Comment by fangxin2github** [comment]
> 你好，我遇到了同样的问题，请问你解决了吗？ @fangxin2github

如果你也是h20显卡的话，试一下pip install nvidia-cublas-cu12==12.4.5.8
