### ISSUE TITLE
[Bug] RuntimeError: shape '[-1, 0]' is invalid for input of size 77

### ISSUE THREAD

**Issue by tcexeexe** [OpenGVLab/InternVL#585]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

I try to run de demo of `Inference with Transformers`
<img width="960" alt="微信图片_20240915212510" src="https://github.com/user-attachments/assets/0af35941-aece-40b2-b7ff-14c082304a48">

but an error occurred that
'''
root@autodl-container-7b4241a946-fd341c95:~# python test.py
FlashAttention2 is not installed.
`flash-attention` package not found, consider installing for better performance: No module named 'flash_attn'.
Current `flash-attenton` does not support `window_size`. Either upgrade or use `attn_implementation='eager'`.
Warning: Flash attention is not available, using eager attention instead.
Warning: Flash attention is not available, using eager attention instead.
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 12.92it/s]
The `seen_tokens` attribute is deprecated and will be removed in v4.41. Use the `cache_position` model input instead.
Traceback (most recent call last):
  File "/root/test.py", line 100, in <module>
    response, history = model.chat(tokenizer, None, question, generation_config, history=None, return_history=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_internvl_chat.py", line 289, in chat
    generation_output = self.generate(
                        ^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_internvl_chat.py", line 339, in generate
    outputs = self.language_model.generate(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/transformers/generation/utils.py", line 2024, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/transformers/generation/utils.py", line 2982, in _sample
    outputs = self(**model_inputs, return_dict=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_phi3.py", line 1290, in forward
    outputs = self.model(
              ^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.cache/huggingface/modules/transformers_modules/InternVL2-4B/modeling_phi3.py", line 1119, in forward
    position_ids = position_ids.view(-1, seq_length).long()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: shape '[-1, 0]' is invalid for input of size 77
'''

Do you know what's wrong with it?

### Environment

```Shell
InternVL2-4B
cuda-12.1
pytorch 2.3.0+cu121
nvidia L20
ubuntu22.04
```

**Comment by hhaAndroid** [comment]
@tcexeexe 

https://huggingface.co/OpenGVLab/InternVL2-4B/blob/main/modeling_phi3.py#L1373

```shell
if inputs_embeds is not None and past_key_values is None:
    model_inputs = {"inputs_embeds": inputs_embeds}
else:
```
to 

```shell
if (inputs_embeds is not None and past_key_values is None) or (inputs_embeds is not None and len(past_key_values)==0):
    model_inputs = {"inputs_embeds": inputs_embeds}
else:
```

**Comment by tcexeexe** [comment]
ok ,it's work

**Comment by czczup** [comment]
I will merge this code into our HF code today.
