### ISSUE TITLE
[Bug] When trying to inference, RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same

### ISSUE THREAD

**Issue by Drosrin** [OpenGVLab/InternVL#602]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [X] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

When trying to inference with InternVL2.0 using https://internvl.readthedocs.io/en/latest/internvl2.0/quick_start.html, I encountered with the problem above. 
I can solve it if the `flash_attn` is not installed by turning `torch_dtype=torch.bfloat16` to `torch_dtype=torch.float32`. However, if `flash_attn` is installed, this method won't work because `flash_attn` only supports bf16 and fp16. As I have tried, changing `flash_attn` version won't work.
Is there anywhere I've done wrong or is there anything I miss?

### Reproduction

This is the `run.py` file I used to inference:
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = '0,1,2,3'
import math
import torch
from transformers import AutoTokenizer, AutoModel

# Split

def split_model(model_name):
    device_map = {}
    world_size = torch.cuda.device_count()
    num_layers = {
        'InternVL2-1B': 24, 'InternVL2-2B': 24, 'InternVL2-4B': 32, 'InternVL2-8B': 32,
        'InternVL2-26B': 48, 'InternVL2-40B': 60, 'InternVL2-Llama3-76B': 80}[model_name]
    # Since the first GPU will be used for ViT, treat it as half a GPU.
    num_layers_per_gpu = math.ceil(num_layers / (world_size - 0.5))
    num_layers_per_gpu = [num_layers_per_gpu] * world_size
    num_layers_per_gpu[0] = math.ceil(num_layers_per_gpu[0] * 0.5)
    layer_cnt = 0
    for i, num_layer in enumerate(num_layers_per_gpu):
        for j in range(num_layer):
            device_map[f'language_model.model.layers.{layer_cnt}'] = i
            layer_cnt += 1
    device_map['vision_model'] = 0
    device_map['mlp1'] = 0
    device_map['language_model.model.tok_embeddings'] = 0
    device_map['language_model.model.embed_tokens'] = 0
    device_map['language_model.output'] = 0
    device_map['language_model.model.norm'] = 0
    device_map['language_model.lm_head'] = 0
    device_map[f'language_model.model.layers.{num_layers - 1}'] = 0

    return device_map

import numpy as np
import torch
import torchvision.transforms as T
from PIL import Image
from torchvision.transforms.functional import InterpolationMode
from transformers import AutoModel, AutoTokenizer

# Inference

IMAGENET_MEAN = (0.485, 0.456, 0.406)
IMAGENET_STD = (0.229, 0.224, 0.225)

def build_transform(input_size):
    MEAN, STD = IMAGENET_MEAN, IMAGENET_STD
    transform = T.Compose([
        T.Lambda(lambda img: img.convert('RGB') if img.mode != 'RGB' else img),
        T.Resize((input_size, input_size), interpolation=InterpolationMode.BICUBIC),
        T.ToTensor(),
        T.Normalize(mean=MEAN, std=STD)
    ])
    return transform

def find_closest_aspect_ratio(aspect_ratio, target_ratios, width, height, image_size):
    best_ratio_diff = float('inf')
    best_ratio = (1, 1)
    area = width * height
    for ratio in target_ratios:
        target_aspect_ratio = ratio[0] / ratio[1]
        ratio_diff = abs(aspect_ratio - target_aspect_ratio)
        if ratio_diff < best_ratio_diff:
            best_ratio_diff = ratio_diff
            best_ratio = ratio
        elif ratio_diff == best_ratio_diff:
            if area > 0.5 * image_size * image_size * ratio[0] * ratio[1]:
                best_ratio = ratio
    return best_ratio

def dynamic_preprocess(image, min_num=1, max_num=12, image_size=448, use_thumbnail=False):
    orig_width, orig_height = image.size
    aspect_ratio = orig_width / orig_height

    # calculate the existing image aspect ratio
    target_ratios = set(
        (i, j) for n in range(min_num, max_num + 1) for i in range(1, n + 1) for j in range(1, n + 1) if
        i * j <= max_num and i * j >= min_num)
    target_ratios = sorted(target_ratios, key=lambda x: x[0] * x[1])

    # find the closest aspect ratio to the target
    target_aspect_ratio = find_closest_aspect_ratio(
        aspect_ratio, target_ratios, orig_width, orig_height, image_size)

    # calculate the target width and height
    target_width = image_size * target_aspect_ratio[0]
    target_height = image_size * target_aspect_ratio[1]
    blocks = target_aspect_ratio[0] * target_aspect_ratio[1]

    # resize the image
    resized_img = image.resize((target_width, target_height))
    processed_images = []
    for i in range(blocks):
        box = (
            (i % (target_width // image_size)) * image_size,
            (i // (target_width // image_size)) * image_size,
            ((i % (target_width // image_size)) + 1) * image_size,
            ((i // (target_width // image_size)) + 1) * image_size
        )
        # split the image
        split_img = resized_img.crop(box)
        processed_images.append(split_img)
    assert len(processed_images) == blocks
    if use_thumbnail and len(processed_images) != 1:
        thumbnail_img = image.resize((image_size, image_size))
        processed_images.append(thumbnail_img)
    return processed_images

def load_image(image_file, input_size=448, max_num=12):
    image = Image.open(image_file).convert('RGB')
    transform = build_transform(input_size=input_size)
    images = dynamic_preprocess(image, image_size=input_size, use_thumbnail=True, max_num=max_num)
    pixel_values = [transform(image) for image in images]
    pixel_values = torch.stack(pixel_values)
    return pixel_values

path = "pretrained/InternVL2-8B"
device_map = split_model('InternVL2-8B')
model = AutoModel.from_pretrained(
    path,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    use_flash_attn=True,
    trust_remote_code=True,
    device_map=device_map).eval()
tokenizer = AutoTokenizer.from_pretrained(path, trust_remote_code=True, use_fast=False)

pixel_values = load_image("pretrained/InternVL2-8B/examples/image1.jpg")
generation_config = dict(max_new_tokens=1024, do_sample=False)

question = '<image>\nPlease supply a fluid and comprehensive depiction of the figures within this image and their interconnections. The numerical data provided here pertains to specific shapes, distinguished by their relative placement. In your description, be sure to accurately convey where the shapes are situated on the canvas.'
response, history = model.chat(tokenizer, pixel_values, question, generation_config, history=None, return_history=True)
print(f'User: {question}\nAssistant: {response}')
```

### Environment

```Shell
All requirements is installed by method `pip install -r requirements.txt` plus flashattn==2.3.6
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "/home/nfs02/model/internvl_2.0/InternVL/run.py", line 137, in <module>
    response, history = model.chat(tokenizer, pixel_values, question, generation_config, history=None, return_history=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xingsy/.cache/huggingface/modules/transformers_modules/internvl_fntn1/modeling_internvl_chat.py", line 289, in chat
    generation_output = self.generate(
                        ^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/xingsy/.cache/huggingface/modules/transformers_modules/internvl_fntn1/modeling_internvl_chat.py", line 325, in generate
    vit_embeds = self.extract_feature(pixel_values)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xingsy/.cache/huggingface/modules/transformers_modules/internvl_fntn1/modeling_internvl_chat.py", line 184, in extract_feature
    vit_embeds = self.vision_model(
                 ^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xingsy/.cache/huggingface/modules/transformers_modules/internvl_fntn1/modeling_intern_vit.py", line 411, in forward
    hidden_states = self.embeddings(pixel_values)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/xingsy/.cache/huggingface/modules/transformers_modules/internvl_fntn1/modeling_intern_vit.py", line 164, in forward
    patch_embeds = self.patch_embedding(pixel_values)  # shape = [*, channel, width, height]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/accelerate/hooks.py", line 169, in new_forward
    output = module._old_forward(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/data_91_c/xsy/torch23py311/lib/python3.11/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Input type (float) and bias type (c10::BFloat16) should be the same
```

**Comment by qishisuren123** [comment]
Please provide a list of the versions of the installed libraries, with a focus on PyTorch and Transformers. This information will be helpful in troubleshooting any potential issues.

**Comment by Drosrin** [comment]
I'm dumb, i loaded the image in wrong way :(

**Comment by awakenlee180** [comment]
> I'm dumb, i loaded the image in wrong way :(

最后怎么解决的呀 我和你的问题是一样的

**Comment by Drosrin** [comment]
> > I'm dumb, i loaded the image in wrong way :(
> 
> 最后怎么解决的呀 我和你的问题是一样的

仔细看一下给的例子 我记得我是没有做一个转换 和例子完全一致应该不会有错

**Comment by awakenlee180** [comment]
> > > I'm dumb, i loaded the image in wrong way :(
> > 
> > 
> > 最后怎么解决的呀 我和你的问题是一样的
> 
> 仔细看一下给的例子 我记得我是没有做一个转换 和例子完全一致应该不会有错

pixel_values = load_image('./examples/image1.jpg', max_num=12).to(torch.bfloat16).cuda()这一块是吧？

**Comment by Drosrin** [comment]
> > > > I'm dumb, i loaded the image in wrong way :(
> > > 
> > > 
> > > 最后怎么解决的呀 我和你的问题是一样的
> > 
> > 
> > 仔细看一下给的例子 我记得我是没有做一个转换 和例子完全一致应该不会有错
> 
> pixel_values = load_image('./examples/image1.jpg', max_num=12).to(torch.bfloat16).cuda()这一块是吧？

对 如果不一样的话抱歉帮不上忙 : (可以试一下不用flashattn然后改成float32(我在描述中提到的方法)

**Comment by awakenlee180** [comment]
> > > > > I'm dumb, i loaded the image in wrong way :(
> > > > 
> > > > 
> > > > 最后怎么解决的呀 我和你的问题是一样的
> > > 
> > > 
> > > 仔细看一下给的例子 我记得我是没有做一个转换 和例子完全一致应该不会有错
> > 
> > 
> > pixel_values = load_image('./examples/image1.jpg', max_num=12).to(torch.bfloat16).cuda()这一块是吧？
> 
> 对 如果不一样的话抱歉帮不上忙 : (可以试一下不用flashattn然后改成float32(我在描述中提到的方法)

我是在fine-tune的时候遇到的问题 不是推理的时候 fine-tune用了flashattn

**Comment by cpy0029** [comment]
> > > > > > I'm dumb, i loaded the image in wrong way :(
> > > > > 
> > > > > 
> > > > > 最后怎么解决的呀 我和你的问题是一样的
> > > > 
> > > > 
> > > > 仔细看一下给的例子 我记得我是没有做一个转换 和例子完全一致应该不会有错
> > > 
> > > 
> > > pixel_values = load_image('./examples/image1.jpg', max_num=12).to(torch.bfloat16).cuda()这一块是吧？
> > 
> > 
> > 对 如果不一样的话抱歉帮不上忙 : (可以试一下不用flashattn然后改成float32(我在描述中提到的方法)
> 
> 我是在fine-tune的时候遇到的问题 不是推理的时候 fine-tune用了flashattn

一样的问题，你最后解决了吗
