### ISSUE TITLE
[Bug]  Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!

### ISSUE THREAD

**Issue by snowattitude** [OpenGVLab/InternVL#760]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

when i used the Inference with Transformers's code with Multiple GPUs , the bug had taken.

### error is 

```Shell
FlashAttention2 is not installed.
Warning: Flash attention is not available, using eager attention instead.
You shouldn't move a model that is dispatched using accelerate hooks.
Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Traceback (most recent call last):
  File "/data2/libolin/InternVL-main/test.py", line 136, in <module>
    response = model.chat(tokenizer, pixel_values, question, generation_config)
  File "/home/libolin/.cache/huggingface/modules/transformers_modules/InternVL2_5-2B/modeling_internvl_chat.py", line 291, in chat
    generation_output = self.generate(
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/libolin/.cache/huggingface/modules/transformers_modules/InternVL2_5-2B/modeling_internvl_chat.py", line 340, in generate
    outputs = self.language_model.generate(
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/transformers/generation/utils.py", line 1479, in generate
    return self.greedy_search(
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/transformers/generation/utils.py", line 2340, in greedy_search
    outputs = self(
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/libolin/.cache/huggingface/modules/transformers_modules/InternVL2_5-2B/modeling_internlm2.py", line 1068, in forward
    outputs = self.model(
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/libolin/.cache/huggingface/modules/transformers_modules/InternVL2_5-2B/modeling_internlm2.py", line 953, in forward
    layer_outputs = decoder_layer(
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/libolin/.cache/huggingface/modules/transformers_modules/InternVL2_5-2B/modeling_internlm2.py", line 653, in forward
    hidden_states = self.attention_norm(hidden_states)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "/data2/libolin/anaconda3/envs/internvl2.5/lib/python3.9/site-packages/accelerate/hooks.py", line 170, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/libolin/.cache/huggingface/modules/transformers_modules/InternVL2_5-2B/modeling_internlm2.py", line 143, in forward
    return self.weight * hidden_states.to(input_dtype)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
```
i used mode is "InternVL2_5-2B"
i install the environment on conda:transformers ==  4.37.2  
gpu: Tesla P100-PCIE-16GB*4

How can I solve this problem?

Thanks！！

**Comment by snowattitude** [comment]
sorry i take the pretrain on the gpu
