### ISSUE TITLE
[Bug] 在复现MPO实验代码时总是遇到程序突然终止，通过日志无法追溯bug到底发生在哪。

### ISSUE THREAD

**Issue by zhangzef** [OpenGVLab/InternVL#800]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [X] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

感谢作者提供非常棒的高质量开源工作！！！
但是我在复现MPO的实验时突然遇到了一个问题，当我在单机八卡h100服务器上复现MPO的实验时会经常遇到模型训练到一半时突然发生如下bug导致程序突然终止，通过log无法判断是什么问题（有一次出现数据集缺少一张RLAIF-V的图像导致在load图像时发现加载失败导致程序终止时的log与下面相同，但是会多一行failed to load image 。。。后来我补上图像后这个问题就没再出现了，但是训练了15小时后程序又出现这样的问题，但是没有其它额外的信息提示问题所在）：

```bash
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
petrel_client is not installed. Using PIL to load images.
Traceback (most recent call last):
  File "/root/paddlejob/workspace/output/zzf/codes/InternVL/internvl_chat/internvl/train/internvl_chat_dpo.py", line 1141, in <module>
    main()
  File "/root/paddlejob/workspace/output/zzf/codes/InternVL/internvl_chat/internvl/train/internvl_chat_dpo.py", line 1126, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/trainer.py", line 1859, in train
    return inner_training_loop(
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/transformers/trainer.py", line 3147, in training_step
    self.accelerator.backward(loss)
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/accelerate/accelerator.py", line 2240, in backward
    self.deepspeed_engine_wrapped.backward(loss, **kwargs)
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/accelerate/utils/deepspeed.py", line 255, in backward
    self.engine.step()
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2169, in step
    self._take_model_step(lr_kwargs)
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/engine.py", line 2075, in _take_model_step
    self.optimizer.step()
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1842, in step
    scaled_global_grad_norm = self.scaled_global_norm()
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/deepspeed/runtime/zero/stage_1_and_2.py", line 1789, in scaled_global_norm
    return torch.norm(torch.stack(norm_groups), p=norm_type)
  File "/root/miniconda3/envs/internvl/lib/python3.9/site-packages/torch/functional.py", line 1611, in norm
    return torch.linalg.vector_norm(input, _p, _dim, keepdim, dtype=dtype)
RuntimeError: linalg.vector_norm: Expected a floating point or complex tensor as input. Got Long
```

### Reproduction

```shell
set -x

PARTITION=${PARTITION:-"Intern5"}
GPUS=${GPUS:-8}
GPUS_PER_NODE=${GPUS_PER_NODE:-8}
QUOTA_TYPE=${QUOTA_TYPE:-"reserved"}
NODES=$((GPUS / GPUS_PER_NODE))
CPUS_PER_TASK=${CPUS_PER_TASK:-10}
SRUN_ARGS=${SRUN_ARGS:-""}
BATCH_SIZE=${BATCH_SIZE:-256}
PER_DEVICE_BATCH_SIZE=${PER_DEVICE_BATCH_SIZE:-1}
GRADIENT_ACC=$((BATCH_SIZE / PER_DEVICE_BATCH_SIZE / GPUS))

# export PYTHONPATH="/mnt/petrelfs/wangweiyun/workspace_cz/InternVL/internvl_chat_dev/petrel-oss-python-sdk"
# export PYTHONPATH="${PYTHONPATH}:$(pwd)"
export MASTER_PORT=34229
export TF_CPP_MIN_LOG_LEVEL=3

OUTPUT_DIR='work_dirs/internvl_chat_v2_0/internvl2_8b_internlm2_7b_dynamic_res_mpo_full'

if [ ! -d "$OUTPUT_DIR" ]; then
  mkdir -p "$OUTPUT_DIR"
fi


deepspeed \
  --num_gpus=${GPUS_PER_NODE} \
  internvl/train/internvl_chat_dpo.py \
  --model_name_or_path "../pretrained/InternVL2-8B" \
  --conv_style "internlm2-chat" \
  --output_dir ${OUTPUT_DIR} \
  --meta_path "../data/MMPR/meta.json" \
  --overwrite_output_dir True \
  --force_image_size 448 \
  --down_sample_ratio 0.5 \
  --drop_path_rate 0.1 \
  --pad2square False \
  --freeze_llm False \
  --freeze_mlp False \
  --freeze_backbone False \
  --vision_select_layer -1 \
  --use_data_resampling False \
  --dataloader_num_workers 8 \
  --bf16 True \
  --num_train_epochs 1 \
  --per_device_train_batch_size ${PER_DEVICE_BATCH_SIZE} \
  --gradient_accumulation_steps ${GRADIENT_ACC} \
  --evaluation_strategy "no" \
  --save_strategy "epoch" \
  --save_steps 100 \
  --save_total_limit 100 \
  --learning_rate 5e-6 \
  --weight_decay 0.05 \
  --warmup_ratio 0.03 \
  --lr_scheduler_type "cosine" \
  --logging_steps 1 \
  --max_seq_length 6144 \
  --do_train True \
  --grad_checkpoint True \
  --group_by_length False \
  --dynamic_image_size True \
  --use_thumbnail True \
  --ps_version 'v2' \
  --deepspeed "zero_stage2_offload_config.json" \
  --report_to "tensorboard" \
  --loss_type sigmoid,bco_pair \
  --sigmoid_loss_weight 0.8 \
  --bco_pair_loss_weight 0.2 \
  --rpo_alpha 1 \
  2>&1 | tee -a "${OUTPUT_DIR}/training_log.txt"
```

### Environment

```Shell
accelerate                1.2.1                    pypi_0    pypi
datasets                  3.2.0                    pypi_0    pypi
deepspeed                 0.13.5                   pypi_0    pypi
flash-attn                2.6.3                    pypi_0    pypi
huggingface-hub           0.27.0                   pypi_0    pypi
python                    3.9.21               he870216_1  
tensorboard               2.18.0                   pypi_0    pypi
tokenizers                0.19.1                   pypi_0    pypi
torch                     2.1.0+cu121              pypi_0    pypi
torchaudio                2.1.0+cu121              pypi_0    pypi
torchvision               0.16.0+cu121             pypi_0    pypi
transformers              4.40.0                   pypi_0    pypi
trl                       0.10.1                   pypi_0    pypi
```

**Comment by zhangzef** [comment]
并且我发现下面两行警告只有在程序被突然终止时会出现大量提示（如我在issue中的log），在正常训练过程中不会出现
```bash
petrel_client is not installed. Using PIL to load images.
petrel_client is not installed. If you read data locally instead of from ceph, ignore it.
```

**Comment by xmy0916** [comment]
看看内存的变化 有可能是内存满了

**Comment by zhangzef** [comment]
> 看看内存的变化 有可能是内存满了

你遇到同样的问题了吗，目前这个bug的复现成本有些高，在八卡服务器上需要训练到16小时左右才会出现这个bug

**Comment by huayicong23** [comment]
@zhangzef 请问你解决了吗，我遇到了类似的问题
