### ISSUE TITLE
[Bug] Finetune for InternVL2-8B loss =13.6234, grad = nan

### ISSUE THREAD

**Issue by codeforplay** [OpenGVLab/InternVL#802]
### Checklist

- [X] 1. I have searched related issues but cannot get the expected help.
- [ ] 2. The bug has not been fixed in the latest version.
- [ ] 3. Please note that if the bug-related issue you submitted lacks corresponding environment info and a minimal reproducible demo, it will be challenging for us to reproduce and resolve the issue, reducing the likelihood of receiving feedback.

### Describe the bug

When finetune InternVL-8B-MPO for medical use, first batch loss = 13.6234, grad_norm = nan， then loss = 0, grad_norm=nan。 I trace the nan using with torch.autograd.detect_anomaly():
            self.accelerator.backward(loss)
Find that flashattention got nan. Any help for it?

### Reproduction

if get_device_count() == 1 and mode_force_torch_run == False:
            sys.argv[0] = "debug in subprocess is false"
            sysarg_str = commandstr.split(" ")
            dummystr = ""
            while dummystr in sysarg_str:
                sysarg_str.remove(dummystr)
            sysarg = sysarg_str[12:]
            for i in range(len(sysarg)):
                sys.argv.append(sysarg[i])
            from internvl.train.internvl_chat_finetune import train_backbone
            train_backbone()
        else:
            process = subprocess.run(commandstr,shell=True,)
            sys.exit(process.returncode)

### Environment

```Shell
learning_rate=4e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=d:/FinetuneModels/InternVL2-8B-MPO\runs\Dec26_16-33-51_DESKTOP-BDKLEK5,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=1.0,
logging_strategy=steps,
lr_scheduler_kwargs={},
lr_scheduler_type=cosine,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=1.0,
optim=adamw_torch,
optim_args=None,
optim_target_modules=None,
output_dir=d:/FinetuneModels/InternVL2-8B-MPO,
overwrite_output_dir=True,
past_index=-1,
per_device_eval_batch_size=8,
per_device_train_batch_size=1,
prediction_loss_only=False,
push_to_hub=False,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['tensorboard'],
resume_from_checkpoint=None,
run_name=d:/FinetuneModels/InternVL2-8B-MPO,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=20,
save_strategy=steps,
save_total_limit=1,
seed=42,
skip_memory_metrics=True,
split_batches=None,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_mps_device=False,
warmup_ratio=0.03,
warmup_steps=0,
weight_decay=0.01,
)
12/26/2024 16:33:51 - INFO - internvl.train.internvl_chat_finetune - Loading Tokenizer: OpenGVLab/InternVL2-8B-MPO
[INFO|tokenization_utils_base.py:2087] 2024-12-26 16:33:53,074 >> loading file ./tokenizer.model from cache at C:\Users\admin\.cache\huggingface\hub\models--OpenGVLab--InternVL2-8B-MPO\snapshots\1e37f9fb4d7a37e02819b450d163e512ce406bb4\./tokenizer.model
[INFO|tokenization_utils_base.py:2087] 2024-12-26 16:33:53,074 >> loading file added_tokens.json from cache at C:\Users\admin\.cache\huggingface\hub\models--OpenGVLab--InternVL2-8B-MPO\snapshots\1e37f9fb4d7a37e02819b450d163e512ce406bb4\added_tokens.json
[INFO|tokenization_utils_base.py:2087] 2024-12-26 16:33:53,074 >> loading file special_tokens_map.json from cache at C:\Users\admin\.cache\huggingface\hub\models--OpenGVLab--InternVL2-8B-MPO\snapshots\1e37f9fb4d7a37e02819b450d163e512ce406bb4\special_tokens_map.json
[INFO|tokenization_utils_base.py:2087] 2024-12-26 16:33:53,075 >> loading file tokenizer_config.json from cache at C:\Users\admin\.cache\huggingface\hub\models--OpenGVLab--InternVL2-8B-MPO\snapshots\1e37f9fb4d7a37e02819b450d163e512ce406bb4\tokenizer_config.json
[INFO|tokenization_utils_base.py:2087] 2024-12-26 16:33:53,075 >> loading file tokenizer.json from cache at None
[WARNING|logging.py:314] 2024-12-26 16:33:53,194 >> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
12/26/2024 16:33:53 - INFO - internvl.train.internvl_chat_finetune - Loading InternVLChatModel...
[INFO|configuration_utils.py:726] 2024-12-26 16:33:53,590 >> loading configuration file config.json from cache at C:\Users\admin\.cache\huggingface\hub\models--OpenGVLab--InternVL2-8B-MPO\snapshots\1e37f9fb4d7a37e02819b450d163e512ce406bb4\config.json
[INFO|configuration_utils.py:789] 2024-12-26 16:33:53,594 >> Model config InternVLChatConfig {
  "_commit_hash": "1e37f9fb4d7a37e02819b450d163e512ce406bb4",
  "architectures": [
    "InternVLChatModel"
  ],
  "auto_map": {
    "AutoConfig": "OpenGVLab/InternVL2-8B-MPO--configuration_internvl_chat.InternVLChatConfig",
    "AutoModel": "OpenGVLab/InternVL2-8B-MPO--modeling_internvl_chat.InternVLChatModel",
    "AutoModelForCausalLM": "OpenGVLab/InternVL2-8B-MPO--modeling_internvl_chat.InternVLChatModel"
  },
  "downsample_ratio": 0.5,
  "dynamic_image_size": true,
  "force_image_size": 448,
  "hidden_size": 4096,
  "llm_config": {
    "_name_or_path": "internlm/internlm2_5-7b-chat",
    "add_cross_attention": false,
    "architectures": [
      "InternLM2ForCausalLM"
    ],
    "attn_implementation": "flash_attention_2",
    "auto_map": {
      "AutoConfig": "configuration_internlm2.InternLM2Config",
      "AutoModel": "modeling_internlm2.InternLM2ForCausalLM",
      "AutoModelForCausalLM": "modeling_internlm2.InternLM2ForCausalLM"
    },
    "bad_words_ids": null,
    "begin_suppress_tokens": null,
    "bias": false,
    "bos_token_id": 1,
    "chunk_size_feed_forward": 0,
    "cross_attention_hidden_size": null,
    "decoder_start_token_id": null,
    "diversity_penalty": 0.0,
    "do_sample": false,
    "early_stopping": false,
    "encoder_no_repeat_ngram_size": 0,
    "eos_token_id": 2,
    "exponential_decay_length_penalty": null,
    "finetuning_task": null,
    "forced_bos_token_id": null,
    "forced_eos_token_id": null,
    "hidden_act": "silu",
    "hidden_size": 4096,
    "id2label": {
      "0": "LABEL_0",
      "1": "LABEL_1"
    },
    "initializer_range": 0.02,
    "intermediate_size": 14336,
    "is_decoder": false,
    "is_encoder_decoder": false,
    "label2id": {
      "LABEL_0": 0,
      "LABEL_1": 1
    },
    "length_penalty": 1.0,
    "max_length": 20,
    "max_position_embeddings": 32768,
    "min_length": 0,
    "model_type": "internlm2",
    "no_repeat_ngram_size": 0,
    "num_attention_heads": 32,
    "num_beam_groups": 1,
    "num_beams": 1,
    "num_hidden_layers": 32,
    "num_key_value_heads": 8,
    "num_return_sequences": 1,
    "output_attentions": false,
    "output_hidden_states": false,
    "output_scores": false,
    "pad_token_id": 2,
    "prefix": null,
    "pretraining_tp": 1,
    "problem_type": null,
    "pruned_heads": {},
    "remove_invalid_values": false,
    "repetition_penalty": 1.0,
    "return_dict": true,
    "return_dict_in_generate": false,
    "rms_norm_eps": 1e-05,
    "rope_scaling": {
      "factor": 2.0,
      "type": "dynamic"
    },
    "rope_theta": 1000000,
    "sep_token_id": null,
    "suppress_tokens": null,
    "task_specific_params": null,
    "temperature": 1.0,
    "tf_legacy_loss": false,
    "tie_encoder_decoder": false,
    "tie_word_embeddings": false,
    "tokenizer_class": null,
    "top_k": 50,
    "top_p": 1.0,
    "torch_dtype": "bfloat16",
    "torchscript": false,
    "transformers_version": "4.40.2",
    "typical_p": 1.0,
    "use_bfloat16": true,
    "use_cache": true,
    "vocab_size": 92553
  },
  "max_dynamic_patch": 12,
  "min_dynamic_patch": 1,
  "model_type": "internvl_chat",
  "pad2square": false,
  "ps_version": "v2",
  "select_layer": -1,
  "template": "internlm2-chat",
  "tie_word_embeddings": false,
  "torch_dtype": "bfloat16",
  "transformers_version": null,
  "use_backbone_lora": 0,
  "use_llm_lora": 0,
  "use_thumbnail": true,
  "vision_config": {
    "_name_or_path": "",
    "add_cross_attention": false,
    "architectures": [
      "InternVisionModel"
    ],
    "attention_dropout": 0.0,
    "bad_words_ids": null,
    "begin_suppress_tokens": null,
    "bos_token_id": null,
    "chunk_size_feed_forward": 0,
    "cross_attention_hidden_size": null,
    "decoder_start_token_id": null,
    "diversity_penalty": 0.0,
    "do_sample": false,
    "drop_path_rate": 0.0,
    "dropout": 0.0,
    "early_stopping": false,
    "encoder_no_repeat_ngram_size": 0,
    "eos_token_id": null,
    "exponential_decay_length_penalty": null,
    "finetuning_task": null,
    "forced_bos_token_id": null,
    "forced_eos_token_id": null,
    "hidden_act": "gelu",
    "hidden_size": 1024,
    "id2label": {
      "0": "LABEL_0",
      "1": "LABEL_1"
    },
    "image_size": 448,
    "initializer_factor": 1.0,
    "initializer_range": 0.02,
    "intermediate_size": 4096,
    "is_decoder": false,
    "is_encoder_decoder": false,
    "label2id": {
      "LABEL_0": 0,
      "LABEL_1": 1
    },
    "layer_norm_eps": 1e-06,
    "length_penalty": 1.0,
    "max_length": 20,
    "min_length": 0,
    "model_type": "intern_vit_6b",
    "no_repeat_ngram_size": 0,
    "norm_type": "layer_norm",
    "num_attention_heads": 16,
    "num_beam_groups": 1,
    "num_beams": 1,
    "num_channels": 3,
    "num_hidden_layers": 24,
    "num_return_sequences": 1,
    "output_attentions": false,
    "output_hidden_states": false,
    "output_scores": false,
    "pad_token_id": null,
    "patch_size": 14,
    "prefix": null,
    "problem_type": null,
    "pruned_heads": {},
    "qk_normalization": false,
    "qkv_bias": true,
    "remove_invalid_values": false,
    "repetition_penalty": 1.0,
    "return_dict": true,
    "return_dict_in_generate": false,
    "sep_token_id": null,
    "suppress_tokens": null,
    "task_specific_params": null,
    "temperature": 1.0,
    "tf_legacy_loss": false,
    "tie_encoder_decoder": false,
    "tie_word_embeddings": true,
    "tokenizer_class": null,
    "top_k": 50,
    "top_p": 1.0,
    "torch_dtype": "bfloat16",
    "torchscript": false,
    "transformers_version": "4.40.2",
    "typical_p": 1.0,
    "use_bfloat16": true,
    "use_flash_attn": true
  }
```

### Error traceback

```Shell
Traceback (most recent call last):
  File "D:\develop\InternVL2-8B-MPO\infer_backbone.py", line 428, in <module>
    backbone_main()
  File "D:\develop\InternVL2-8B-MPO\infer_backbone.py", line 422, in backbone_main
    train_backbone()
  File "D:\develop\InternVL2-8B-MPO\internvl\train\internvl_chat_finetune.py", line 1129, in train_backbone
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\transformers\trainer.py", line 1859, in train
    return inner_training_loop(
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\transformers\trainer.py", line 2203, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "D:\develop\InternVL2-8B-MPO\internvl\train\internvl_chat_finetune.py", line 741, in training_step
    self.accelerator.backward(loss)
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\accelerate\accelerator.py", line 2159, in backward
    loss.backward(**kwargs)
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\torch\_tensor.py", line 521, in backward
    torch.autograd.backward(
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\torch\autograd\__init__.py", line 289, in backward
    _engine_run_backward(
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\torch\autograd\graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\torch\autograd\function.py", line 306, in apply
    return user_fn(self, *args)
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\torch\utils\checkpoint.py", line 313, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\torch\autograd\__init__.py", line 289, in backward
    _engine_run_backward(
  File "c:\ProgramData\anaconda3\envs\pytorchcp310cu124\lib\site-packages\torch\autograd\graph.py", line 768, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Function 'FlashAttnFuncBackward' returned nan values in its 2th output.
```

**Comment by codeforplay** [comment]
My environment is as follows:
Package                  Version
------------------------ ------------
absl-py                  2.1.0
accelerate               0.33.0
aiofiles                 23.2.1
aiohappyeyeballs         2.4.0
aiohttp                  3.10.5
aiosignal                1.3.1
annotated-types          0.7.0
anyio                    4.4.0
async-timeout            4.0.3
attrs                    24.2.0
auto-gptq                0.4.2
bitsandbytes             0.43.3
certifi                  2024.7.4
charset-normalizer       3.3.2
click                    8.1.7
colorama                 0.4.6
coloredlogs              15.0.1
datasets                 2.21.0
decord                   0.6.0
dill                     0.3.8
einops                   0.8.0
evaluate                 0.4.3
exceptiongroup           1.2.2
fastapi                  0.115.5
ffmpeg                   1.4
ffmpy                    0.4.0
filelock                 3.13.1
flash_attn               2.7.1.post1
frozenlist               1.4.1
fsspec                   2024.2.0
gekko                    1.2.1
gradio                   5.6.0
gradio_client            1.4.3
greenlet                 3.0.3
grpcio                   1.68.1
h11                      0.14.0
httpcore                 1.0.5
httpx                    0.27.0
huggingface-hub          0.26.2
humanfriendly            10.0
idna                     3.8
imageio                  2.36.1
Jinja2                   3.1.3
joblib                   1.4.2
jsonpatch                1.33
jsonpointer              3.0.0
langchain                0.2.14
langchain-core           0.2.35
langchain-text-splitters 0.2.2
langsmith                0.1.104
Markdown                 3.7
markdown-it-py           3.0.0
MarkupSafe               2.1.5
mdurl                    0.1.2
mpmath                   1.3.0
multidict                6.0.5
multiprocess             0.70.16
networkx                 3.2.1
numpy                    1.26.3
opencv-python            4.10.0.84
optimum                  1.21.4
orjson                   3.10.7
packaging                24.1
pandas                   2.2.2
peft                     0.5.0
pillow                   10.2.0
pip                      24.2
protobuf                 5.27.3
psutil                   6.0.0
pyarrow                  17.0.0
pydantic                 2.8.2
pydantic_core            2.20.1
pydub                    0.25.1
Pygments                 2.18.0
pyreadline3              3.4.1
python-dateutil          2.9.0.post0
python-multipart         0.0.12
pytz                     2024.1
PyYAML                   6.0.2
regex                    2024.7.24
requests                 2.32.3
rich                     13.9.4
rouge                    1.0.1
ruff                     0.7.4
safehttpx                0.1.1
safetensors              0.4.4
scikit-learn             1.5.2
scipy                    1.14.1
semantic-version         2.10.0
sentencepiece            0.2.0
setuptools               72.1.0
shellingham              1.5.4
six                      1.16.0
sniffio                  1.3.1
SQLAlchemy               2.0.32
starlette                0.41.2
sympy                    1.12
tenacity                 8.5.0
tensorboard              2.18.0
tensorboard-data-server  0.7.2
threadpoolctl            3.5.0
timm                     1.0.11
tokenizers               0.19.1
tomlkit                  0.12.0
torch                    2.4.0+cu124
torchaudio               2.4.0+cu124
torchvision              0.19.0+cu124
tqdm                     4.66.5
transformers             4.40.2
typer                    0.13.0
typing_extensions        4.9.0
tzdata                   2024.1
urllib3                  2.2.2
uvicorn                  0.32.0
websockets               12.0
Werkzeug                 3.1.3
wheel                    0.43.0
xformers                 0.0.27.post2
xxhash                   3.5.0
yarl                     1.9.4

**Comment by codeforplay** [comment]
Solve it by using 'eager' rather than 'flash_attention_2'。
