### ISSUE TITLE
关于InternVL-Chat-V1-5-Preview的RuntimeError: probability tensor contains either `inf`, `nan` or element < 0 

### ISSUE THREAD

**Issue by a136214808** [OpenGVLab/InternVL#98]
当使用 InternVL-Chat-V1-5-Preview 和 InternVL-main 进行配置时 会报RuntimeError: probability tensor contains either `inf`, `nan` or element < 0 错

**Comment by blackblue9** [comment]
我也遇到了这个问题，报错如下：
`024-04-22 17:16:53 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 2
2024-04-22 17:17:05 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=4, locked=False). global_counter: 3
2024-04-22 17:17:05 | INFO | stdout | INFO:     127.0.0.1:60362 - "POST /worker_generate_stream HTTP/1.1" 200 OK
2024-04-22 17:17:05 | INFO | model_worker | Resize images to 448x448
2024-04-22 17:17:05 | INFO | model_worker | A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions. USER: <img><image></img>
这个图里有啥 ASSISTANT:
2024-04-22 17:17:05 | INFO | model_worker | num_image_tokens: 256
2024-04-22 17:17:05 | ERROR | stderr | Exception in thread Thread-5 (generate):
2024-04-22 17:17:05 | ERROR | stderr | Traceback (most recent call last):
2024-04-22 17:17:05 | ERROR | stderr |   File "/usr/local/miniconda3/envs/intervl/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
2024-04-22 17:17:05 | ERROR | stderr |     self.run()
2024-04-22 17:17:05 | ERROR | stderr |   File "/usr/local/miniconda3/envs/intervl/lib/python3.10/threading.py", line 953, in run
2024-04-22 17:17:05 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2024-04-22 17:17:05 | ERROR | stderr |   File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-04-22 17:17:05 | ERROR | stderr |     return func(*args, **kwargs)
2024-04-22 17:17:05 | ERROR | stderr |   File "/mnt/tenant-home_speed/qxj/MLLM/InternVL-main/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py", line 260, in generate
2024-04-22 17:17:05 | ERROR | stderr |     outputs = self.language_model.generate(
2024-04-22 17:17:05 | ERROR | stderr |   File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
2024-04-22 17:17:05 | ERROR | stderr |     return func(*args, **kwargs)
2024-04-22 17:17:05 | ERROR | stderr |   File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate
2024-04-22 17:17:05 | ERROR | stderr |     return self.sample(
2024-04-22 17:17:05 | ERROR | stderr |   File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/transformers/generation/utils.py", line 2897, in sample
2024-04-22 17:17:05 | ERROR | stderr |     next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
2024-04-22 17:17:05 | ERROR | stderr | RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
2024-04-22 17:17:08 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=4, locked=False). global_counter: 3
2024-04-22 17:17:20 | INFO | stdout | Caught Unknown Error
2024-04-22 17:17:20 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:17:23 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:17:38 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:17:53 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:18:08 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:18:23 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:18:38 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:18:53 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:19:08 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:19:24 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:19:39 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:19:54 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
2024-04-22 17:20:09 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=5, locked=False). global_counter: 3
`

**Comment by a136214808** [comment]
> 我也遇到了这个问题，在运行python -m internvl.serve.model_worker --host 0.0.0.0 --controller http://localhost:10000 --port 40003 --worker http://localhost:40003 --model-path /mnt/InternVL-Chat-V1-5 后，接着在gradio前端运行demo时报错如下： `
> 
> 2024-04-22 17:17:05 | INFO | model_worker | num_image_tokens: 256 2024-04-22 17:17:05 | ERROR | stderr | Exception in thread Thread-5 (generate): 2024-04-22 17:17:05 | ERROR | stderr | Traceback (most recent call last): 2024-04-22 17:17:05 | ERROR | stderr | File "/usr/local/miniconda3/envs/intervl/lib/python3.10/threading.py", line 1016, in _bootstrap_inner 2024-04-22 17:17:05 | ERROR | stderr | self.run() 2024-04-22 17:17:05 | ERROR | stderr | File "/usr/local/miniconda3/envs/intervl/lib/python3.10/threading.py", line 953, in run 2024-04-22 17:17:05 | ERROR | stderr | self._target(*self._args, **self._kwargs) 2024-04-22 17:17:05 | ERROR | stderr | File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context 2024-04-22 17:17:05 | ERROR | stderr | return func(*args, **kwargs) 2024-04-22 17:17:05 | ERROR | stderr | File "/mnt/tenant-home_speed/qxj/MLLM/InternVL-main/internvl_chat/internvl/model/internvl_chat/modeling_internvl_chat.py", line 260, in generate 2024-04-22 17:17:05 | ERROR | stderr | outputs = self.language_model.generate( 2024-04-22 17:17:05 | ERROR | stderr | File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context 2024-04-22 17:17:05 | ERROR | stderr | return func(*args, **kwargs) 2024-04-22 17:17:05 | ERROR | stderr | File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/transformers/generation/utils.py", line 1764, in generate 2024-04-22 17:17:05 | ERROR | stderr | return self.sample( 2024-04-22 17:17:05 | ERROR | stderr | File "/usr/local/miniconda3/envs/intervl/lib/python3.10/site-packages/transformers/generation/utils.py", line 2897, in sample 2024-04-22 17:17:05 | ERROR | stderr | next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1) 2024-04-22 17:17:05 | ERROR | stderr | RuntimeError: probability tensor contains either `inf`, `nan` or element < 0 2024-04-22 17:17:08 | INFO | model_worker | Send heart beat. Models: ['InternVL-Chat-V1-5']. Semaphore: Semaphore(value=4, locked=False). global_counter: 3 2024-04-22 17:17:20 | INFO | stdout | Caught Unknown Error ` 请问应该如何解决呢？？

去下载他们新上传的包应该就可以了，我已经解决了

**Comment by blackblue9** [comment]
已解决，谢谢大佬

**Comment by czczup** [comment]
更新一下最新的代码应该就可以解决这个问题
